@uri = http://localhost:4000/api/courses

### GET ALL COURSES
GET {{uri}}

### GET COURSE BY ID
GET {{uri}}/5fb2d6af97f99e21d12116d2

### CREATE NEW COURSE
POST {{uri}}/5fb0358bca6f0518bd237e7c
Content-Type: application/json

{
    // payload example
    "name": "Curso de Node",
    "image": "/images/node.jpg",
    "description": "Curso de introducción a Node",
    "category": "Backend",
    "lessons": [
      {
        "title": "Introducción al Curso",
        "content": "Node.js es un entorno de ejecución de JavaScript",
        "urlResource": "https://nodejs.org",
      },
    ],
  },

### UPDATE COURSE BY ID
PUT {{uri}}/5fb2d6af97f99e21d12116d2
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmIyZDZhZjk3Zjk5ZTIxZDEyMTE2Y2EiLCJpYXQiOjE2MDU2Nzk0OTAsImV4cCI6MTYwNTc2NTg5MH0.Wv9tGlBnzbnWZD5rKeZE8KQDmMcHpzwKG1jwhFzwitw

{
  "lessons": [
    {
      "_id": "5fb2d6af97f99e21d12116d3",
      "title": "Introducción al Curso",
      "content": "The Progressive JavaScript Framework",
      "urlResource": "https://vuejs.org"
    },
  ]
}

### DELETE COURSE BY ID
DELETE  {{uri}}/5fb0358bca6f0518bd237e7e